### PR TITLE
bug fix: partials do not render on Windows 7.

### PR DESCRIPTION
**Pull request by veryangrymobster**
This is my first pull request for Punch. 

I was attempting to follow the Punch setup tutorial but partials weren't rendering. I found the fix for the 
problem here: https://github.com/laktek/punch/issues/102

My system is Windows 7 64bit. 

Partials are now rendering after applying the fix. I have no idea what effects the changes will have when run on OSX and other operating systems. Sorry.

### CODE REVIEW

**Comment by laktek** [comment]
Thanks for the PR. I'll try to review and test it over the weekend.

Any idea why the diff changes all lines in the file? Can you try to format it to only show the lines that were changed?

**Comment by veryangrymobster** [comment]
I'm not sure why the diff shows all lines as changed. Maybe the line endings have changed? 

Anyway, I noticed the problem with the diff on my first attempt to commit the changes. I reset the commit and did it a second time taking more care. Here you can see the two lines that were changed:
https://github.com/veryangrymobster/punch/compare/laktek:master...master

I didn't expect the diff to still have problems when being compared to your files. To fix it I'll need to delete my fork and start from scratch. As it's only two lines would you mind copying the changes manually?

**Comment by laktek** [comment]
You don't have to delete your fork. You can close the previous PR and open
a new PR with this diff.

**Comment by veryangrymobster** [comment]
Alright, I'll give it a go.

**Pull request closed without merging**
